import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { auth, signOut } from "@/auth";
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ChadRock Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col gap-8 row-start-1 items-center sm:items-start">
            {session?.user ? (
              <form
                action={async () => {
                  "use server";
                  await signOut();
                }}
              >
                <div className="flex items-center gap-2">
                  <button>Logout</button>
                  <Image
                    src={session.user.image || ""}
                    alt={session.user.name || ""}
                    className="rounded-full w-4 h-4 object-cover"
                    width={12}
                    height={12}
                  />
                </div>
              </form>
            ) : (
              <a
              className="rounded-full border border-solid border-transparent transition-colors flex items-center justify-center bg-foreground text-background gap-2 hover:bg-[#383838] dark:hover:bg-[#ccc] text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5"
              href="/login"
              >
                LOGIN
              </a>
            )}
        </div>
        {children}
      </body>
    </html>
  );
}
